language: rust
rust:
  - nightly-2017-05-03

services:
  - postgresql

before_install:
  - npm install -g less
  - cargo install -f diesel_cli

before_script:
  - cp .env.travis .env
  - diesel setup

env:
  - RUSTFLAGS="--deny warnings"

script:
  - ci/check-basic-style.sh
  - cargo build --verbose
  - cargo test --verbose

cache: cargo
