language: rust
rust:
  - nightly

before_install:
  # - sudo apt-get install npm
  - npm install -g less

env:
  - RUSTFLAGS="--deny warnings"

script:
  - ci/check-basic-style.sh
  - cargo build --verbose
  - cargo test --verbose

cache: cargo
